export const MOCK_DATA = {
  classes: [
    { class_name: "Computer Science A", room_name: "Room 101", isLab: false },
    { class_name: "Lab 201", room_name: "Lab 201", isLab: true },
    { class_name: "Mathematics A", room_name: "Room 102", isLab: false },
  ],

  subjects: [
    {
      name: "Mathematics",
      min_classes_day: 1,
      max_classes_day: 2,
      min_classes_week: 4,
      max_classes_week: 5,
      min_classes_consecutive: 1,
      max_classes_consecutive: 2,
      isLab: false,
      lab_classes: null,
      hardness: "High",
      rgb_code: "#FF6B6B",
    },
    {
      name: "Physics",
      min_classes_day: 1,
      max_classes_day: 2,
      min_classes_week: 3,
      max_classes_week: 4,
      min_classes_consecutive: 1,
      max_classes_consecutive: 2,
      isLab: false,
      lab_classes: null,
      hardness: "High",
      rgb_code: "#4ECDC4",
    },
    {
      name: "English",
      min_classes_day: 1,
      max_classes_day: 1,
      min_classes_week: 3,
      max_classes_week: 4,
      min_classes_consecutive: 1,
      max_classes_consecutive: 1,
      isLab: false,
      lab_classes: null,
      hardness: "Low",
      rgb_code: "#FFE66D",
    },
    {
      name: "History",
      min_classes_day: 1,
      max_classes_day: 1,
      min_classes_week: 2,
      max_classes_week: 3,
      min_classes_consecutive: 1,
      max_classes_consecutive: 1,
      isLab: false,
      lab_classes: null,
      hardness: "Low",
      rgb_code: "#A8E6CF",
    },
    {
      name: "Physical Education",
      min_classes_day: 1,
      max_classes_day: 1,
      min_classes_week: 2,
      max_classes_week: 3,
      min_classes_consecutive: 1,
      max_classes_consecutive: 2,
      isLab: false,
      lab_classes: null,
      hardness: "Low",
      rgb_code: "#FF8B94",
    },
    {
      name: "Programming Lab",
      min_classes_day: 1,
      max_classes_day: 2,
      min_classes_week: 4,
      max_classes_week: 6,
      min_classes_consecutive: 2,
      max_classes_consecutive: 2,
      isLab: true,
      lab_classes: [2],
      hardness: "High",
      rgb_code: "#C3B1E1",
    },
    {
      name: "Database Systems",
      min_classes_day: 1,
      max_classes_day: 2,
      min_classes_week: 3,
      max_classes_week: 5,
      min_classes_consecutive: 1,
      max_classes_consecutive: 2,
      isLab: false,
      lab_classes: null,
      hardness: "Med",
      rgb_code: "#FFDAC1",
    },
    {
      name: "Networking Lab",
      min_classes_day: 1,
      max_classes_day: 2,
      min_classes_week: 4,
      max_classes_week: 6,
      min_classes_consecutive: 2,
      max_classes_consecutive: 2,
      isLab: true,
      lab_classes: [2],
      hardness: "Med",
      rgb_code: "#B5EAD7",
    },
    {
      name: "Computer Architecture",
      min_classes_day: 1,
      max_classes_day: 1,
      min_classes_week: 2,
      max_classes_week: 3,
      min_classes_consecutive: 1,
      max_classes_consecutive: 1,
      isLab: false,
      lab_classes: null,
      hardness: "Med",
      rgb_code: "#E2F0CB",
    },
    {
      name: "Advanced Mathematics",
      min_classes_day: 1,
      max_classes_day: 2,
      min_classes_week: 5,
      max_classes_week: 6,
      min_classes_consecutive: 1,
      max_classes_consecutive: 2,
      isLab: false,
      lab_classes: null,
      hardness: "High",
      rgb_code: "#FF9AA2",
    },
    {
      name: "Statistics",
      min_classes_day: 1,
      max_classes_day: 2,
      min_classes_week: 3,
      max_classes_week: 5,
      min_classes_consecutive: 1,
      max_classes_consecutive: 2,
      isLab: false,
      lab_classes: null,
      hardness: "High",
      rgb_code: "#FFB7B2",
    },
    {
      name: "Economics",
      min_classes_day: 1,
      max_classes_day: 1,
      min_classes_week: 3,
      max_classes_week: 4,
      min_classes_consecutive: 1,
      max_classes_consecutive: 1,
      isLab: false,
      lab_classes: null,
      hardness: "Med",
      rgb_code: "#FFEAA7",
    },
    {
      name: "Geography",
      min_classes_day: 1,
      max_classes_day: 1,
      min_classes_week: 2,
      max_classes_week: 3,
      min_classes_consecutive: 1,
      max_classes_consecutive: 1,
      isLab: false,
      lab_classes: null,
      hardness: "Low",
      rgb_code: "#DDA0DD",
    },
    {
      name: "Literature",
      min_classes_day: 1,
      max_classes_day: 1,
      min_classes_week: 2,
      max_classes_week: 3,
      min_classes_consecutive: 1,
      max_classes_consecutive: 1,
      isLab: false,
      lab_classes: null,
      hardness: "Low",
      rgb_code: "#98D8C8",
    },
  ],

  teachers: [
    {
      name: "Dr. Alan Foster",
      max_classes_day: 3,
      max_classes_week: 15,
      max_classes_consecutive: 2,
    }, // id: 1
    {
      name: "Ms. Rachel Simmons",
      max_classes_day: 3,
      max_classes_week: 12,
      max_classes_consecutive: 2,
    }, // id: 2
    {
      name: "Mr. James Whitley",
      max_classes_day: 2,
      max_classes_week: 10,
      max_classes_consecutive: 1,
    }, // id: 3
    {
      name: "Mrs. Laura Hensley",
      max_classes_day: 2,
      max_classes_week: 10,
      max_classes_consecutive: 1,
    }, // id: 4
    {
      name: "Mr. Kevin Nash",
      max_classes_day: 2,
      max_classes_week: 8,
      max_classes_consecutive: 2,
    }, // id: 5
    {
      name: "Ms. Priya Nair",
      max_classes_day: 3,
      max_classes_week: 15,
      max_classes_consecutive: 2,
    }, // id: 6
    {
      name: "Dr. Samuel Okafor",
      max_classes_day: 3,
      max_classes_week: 12,
      max_classes_consecutive: 2,
    }, // id: 7
    {
      name: "Mr. Chris Delgado",
      max_classes_day: 3,
      max_classes_week: 15,
      max_classes_consecutive: 2,
    }, // id: 8
    {
      name: "Dr. Mei Lin",
      max_classes_day: 2,
      max_classes_week: 10,
      max_classes_consecutive: 1,
    }, // id: 9
    {
      name: "Dr. Emily Hartman",
      max_classes_day: 4,
      max_classes_week: 18,
      max_classes_consecutive: 2,
    }, // id: 10
    {
      name: "Mr. Rohan Verma",
      max_classes_day: 3,
      max_classes_week: 15,
      max_classes_consecutive: 2,
    }, // id: 11
    {
      name: "Ms. Clara Mendes",
      max_classes_day: 2,
      max_classes_week: 10,
      max_classes_consecutive: 1,
    }, // id: 12
    {
      name: "Mr. Tom Eriksson",
      max_classes_day: 2,
      max_classes_week: 8,
      max_classes_consecutive: 1,
    }, // id: 13
    {
      name: "Mrs. Sophie Dubois",
      max_classes_day: 2,
      max_classes_week: 8,
      max_classes_consecutive: 1,
    }, // id: 14
  ],

  assignments: [
    {
      teacher_id: 1,
      class_id: 1,
      subject_id: 1,
      role: "Class_Teacher",
      morning_class_days: ["Mon", "Tue", "Wed", "Thu"],
    },
    {
      teacher_id: 2,
      class_id: 1,
      subject_id: 2,
      role: "Subject_Teacher",
      morning_class_days: ["Wed", "Thu"],
    },
    {
      teacher_id: 3,
      class_id: 1,
      subject_id: 3,
      role: "Subject_Teacher",
      morning_class_days: null,
    },
    {
      teacher_id: 4,
      class_id: 1,
      subject_id: 4,
      role: "Subject_Teacher",
      morning_class_days: null,
    },
    {
      teacher_id: 5,
      class_id: 1,
      subject_id: 5,
      role: "Subject_Teacher",
      morning_class_days: ["Fri"],
    },
    {
      teacher_id: 6,
      class_id: 1,
      subject_id: 6,
      role: "Subject_Teacher",
      morning_class_days: ["Mon", "Tue"],
    },
    {
      teacher_id: 7,
      class_id: 1,
      subject_id: 7,
      role: "Subject_Teacher",
      morning_class_days: null,
    },
    {
      teacher_id: 8,
      class_id: 1,
      subject_id: 8,
      role: "Subject_Teacher",
      morning_class_days: ["Wed", "Thu"],
    },
    {
      teacher_id: 9,
      class_id: 1,
      subject_id: 9,
      role: "Subject_Teacher",
      morning_class_days: null,
    },
    {
      teacher_id: 10,
      class_id: 3,
      subject_id: 10,
      role: "Class_Teacher",
      morning_class_days: ["Mon", "Tue", "Wed", "Thu"],
    },
    {
      teacher_id: 11,
      class_id: 3,
      subject_id: 11,
      role: "Subject_Teacher",
      morning_class_days: ["Mon", "Wed"],
    },
    {
      teacher_id: 12,
      class_id: 3,
      subject_id: 12,
      role: "Subject_Teacher",
      morning_class_days: ["Tue"],
    },
    {
      teacher_id: 13,
      class_id: 3,
      subject_id: 13,
      role: "Subject_Teacher",
      morning_class_days: null,
    },
    {
      teacher_id: 14,
      class_id: 3,
      subject_id: 14,
      role: "Subject_Teacher",
      morning_class_days: null,
    },
  ],
};
